### ISSUE TITLE
Won't boot up

### ISSUE THREAD

**Issue by zspri** [GridTech123/GridOS#1]
Freezes after a few seconds and Python console says:
`Traceback (most recent call last):
  File "C:\Users\(my user)\Downloads\GridOS-master\GridOS-master\gridOS\gridOS.py", line 56, in <module>
    from win32api import *
ImportError: DLL load failed: %1 is not a valid Win32 application.`

**Comment by GridTech123** [comment]
you need to install the latest version of win32api. install at https://sourceforge.net/projects/pywin32/files/?source=navbar go to pywin32 then hit build 220(the latest one), choose your version and install as normal.

**Comment by GridTech123** [comment]
I'm running diagnostics for other issues right now

**Comment by GridTech123** [comment]
Remember to also use python 2.7

**Comment by GridTech123** [comment]
that's all the reasons I can see

**Comment by zspri** [comment]
I'll try to re-install it.

**Comment by GridTech123** [comment]
There is now an exe so you don't need to install them but the exe will only be updated for every release NOT commit

**Comment by zspri** [comment]
Ok, thanks.
